// PNG/JPG sources for which AVIF was not generated (alpha channel).
// Browsers will fall back to WebP for these.
const NO_AVIF = new Set([
  '/brand/dotted-circle.png',
  '/brand/icon-brain.png',
  '/brand/icon-build.png',
  '/brand/icon-energy.png',
  '/brand/icon-performance.png',
  '/brand/icon-stress.png',
  '/products/hydra-muscle.png',
  '/products/hydra-muscle-01.png',
  '/products/hydra-muscle-02.jpg',
  '/products/hydra-muscle-03.jpg',
  '/products/hydra-muscle-04.jpg',
  '/products/hydra-muscle-05.jpg',
  '/products/hydra-muscle-06.jpg',
  '/products/hydra-muscle-07.jpg',
  '/products/hydra-muscle-08.jpg',
  '/products/trex-cordyceps.png',
  '/products/trex-ginseng.png',
  '/products/trex-ginseng-01.png',
  '/products/trex-ginseng-02.png',
  '/products/trex-ginseng-03.png',
  '/products/trex-ginseng-04.png',
  '/products/trex-ginseng-05.png',
  '/products/trex-ginseng-06.png',
  '/products/trex-liquid-04.png',
  '/products/trex-liver.png',
  '/products/trex-liver-01.jpeg',
  '/products/trex-liver-02.jpeg',
  '/products/trex-liver-03.jpeg',
  '/products/trex-liver-04.jpeg',
  '/products/trex-liver-05.jpeg',
  '/products/trex-liver-06.jpeg',
  '/products/trex-liver-07.jpeg',
  '/products/trex-maca.png',
  '/products/trex-maca-01.jpeg',
  '/products/trex-maca-02.jpeg',
  '/products/trex-maca-03.jpeg',
  '/products/trex-maca-04.jpeg',
  '/products/trex-maca-05.jpeg',
  '/products/trex-maca-06.jpeg',
  '/products/trex-maca-07.jpeg',
  '/products/trex-royal-jelly.png',
  '/products/trex-royal-jelly-01.jpeg',
  '/products/trex-royal-jelly-02.jpeg',
  '/products/trex-royal-jelly-03.jpeg',
  '/products/trex-royal-jelly-04.jpeg',
  '/products/trex-royal-jelly-05.jpeg',
  '/products/trex-royal-jelly-06.jpeg',
  '/products/trex-royal-jelly-07.jpeg',
  '/products/trex-tongkat.png',
  '/products/trex-tongkat-01.jpeg',
  '/products/trex-tongkat-02.jpeg',
  '/products/trex-tongkat-03.jpeg',
  '/products/trex-tongkat-04.jpeg',
  '/products/trex-tongkat-05.jpeg',
  '/products/trex-tongkat-06.jpeg',
  '/products/trex-tongkat-07.jpeg',
  '/products/forge/trex-maca.jpg',
  '/products/forge/trex-cordyceps.jpg',
  '/products/forge/hydra-muscle.jpg',
  '/products/forge/trex-ginseng.jpg',
  '/products/forge/trex-liver.jpg',
  '/products/forge/trex-royal-jelly.jpg',
  '/products/forge/trex-tongkat.jpg',
  // Sorana Studio new images — no AVIF generated, serve WebP directly
  '/products/trex-royal-jelly-new-01.png',
  '/products/trex-royal-jelly-new-02.png',
  '/products/trex-royal-jelly-new-03.png',
  '/products/trex-royal-jelly-new-04.jpeg',
  '/products/trex-royal-jelly-new-05.jpeg',
  '/products/trex-royal-jelly-new-06.jpeg',
  '/products/trex-royal-jelly-new-07.jpeg',
  '/products/trex-tongkat-new-01.png',
  '/products/trex-tongkat-new-02.png',
  '/products/trex-tongkat-new-03.png',
  '/products/trex-tongkat-new-04.jpeg',
  '/products/trex-tongkat-new-05.jpeg',
  '/products/trex-tongkat-new-06.jpeg',
  '/products/trex-tongkat-new-07.jpeg',
  '/products/trex-maca-new-01.png',
  '/products/trex-maca-new-02.png',
  '/products/trex-maca-new-03.png',
  '/products/trex-maca-new-04.jpeg',
  '/products/trex-maca-new-05.jpeg',
  '/products/trex-maca-new-06.jpeg',
  '/products/trex-maca-new-07.jpeg',
  '/products/trex-cordyceps-new-01.png',
  '/products/trex-cordyceps-new-02.png',
  '/products/trex-cordyceps-new-03.png',
  '/products/trex-cordyceps-new-04.png',
  '/products/trex-ginseng-new-01.png',
  '/products/trex-ginseng-new-02.png',
  '/products/trex-ginseng-new-03.png',
  '/products/trex-ginseng-new-04.jpeg',
  '/products/trex-ginseng-new-05.jpeg',
  '/products/trex-ginseng-new-06.jpeg',
  '/products/trex-ginseng-new-07.jpeg',
  '/products/trex-liver-new-01.png',
  '/products/trex-liver-new-02.png',
  '/products/trex-liver-new-03.png',
  '/products/trex-liver-new-04.png',
  '/products/trex-liver-new-05.jpeg',
  '/products/trex-liver-new-06.jpeg',
  '/products/trex-liver-new-07.jpeg',
  '/products/trex-liver-new-08.jpeg',
  // v2 product images — no AVIF generated (also no WebP — see NO_WEBP below)
  '/products/trex-v2-01.png',
  '/products/trex-v2-02.png',
  '/products/trex-v2-03.png',
  '/products/trex-v2-04.png',
  '/products/trex-v2-05.png',
  '/products/trex-v2-06.jpg',
  '/products/trex-v2-07.png',
  '/products/ginseng-v2-01.png',
  '/products/ginseng-v2-02.png',
  '/products/ginseng-v2-03.png',
  '/products/ginseng-v2-04.jpeg',
  '/products/ginseng-v2-05.jpeg',
  '/products/ginseng-v2-06.jpeg',
  '/products/ginseng-v2-07.jpeg',
  '/products/maca-v2-01.png',
  '/products/maca-v2-02.png',
  '/products/maca-v2-03.png',
  '/products/maca-v2-04.jpeg',
  '/products/maca-v2-05.jpeg',
  '/products/maca-v2-06.jpeg',
  '/products/maca-v2-07.jpeg',
  '/products/cordyceps-v2-01.png',
  '/products/cordyceps-v2-02.png',
  '/products/cordyceps-v2-03.png',
  '/products/cordyceps-v2-04.png',
  '/products/royal-jelly-v2-01.png',
  '/products/royal-jelly-v2-02.png',
  '/products/royal-jelly-v2-03.png',
  '/products/royal-jelly-v2-04.jpeg',
  '/products/royal-jelly-v2-05.jpeg',
  '/products/royal-jelly-v2-06.jpeg',
  '/products/royal-jelly-v2-07.jpeg',
  '/products/tongkat-v2-01.png',
  '/products/tongkat-v2-02.png',
  '/products/tongkat-v2-03.png',
  '/products/tongkat-v2-04.jpeg',
  '/products/tongkat-v2-05.jpeg',
  '/products/tongkat-v2-06.jpeg',
  '/products/tongkat-v2-07.jpeg',
  '/products/liver-v2-01.png',
  '/products/liver-v2-02.png',
  '/products/liver-v2-03.png',
  '/products/liver-v2-04.png',
  '/products/liver-v2-05.jpeg',
  '/products/liver-v2-06.jpeg',
  '/products/liver-v2-07.jpeg',
  '/products/liver-v2-08.jpeg',
  '/brand/shop-hero.jpg',
  '/products/ingredients/shilajit.jpg',
  '/products/ingredients/ashwagandha.jpg',
  '/products/ingredients/arjun.jpg',
  '/products/ingredients/gokhru.jpg',
  '/products/ingredients/draksha.jpg',
  '/products/ingredients/safed-musli.jpg',
  '/products/ingredients/kath-badam.jpg',
])
// Note: /products/trex-liquid.png does have an AVIF — it's rendered without alpha.

// v2 product images have no WebP generated either — skip the <source type="image/webp"> for these.
const NO_WEBP = new Set([
  '/products/trex-v2-01.png',
  '/products/trex-v2-02.png',
  '/products/trex-v2-03.png',
  '/products/trex-v2-04.png',
  '/products/trex-v2-05.png',
  '/products/trex-v2-06.jpg',
  '/products/trex-v2-07.png',
  '/products/ginseng-v2-01.png',
  '/products/ginseng-v2-02.png',
  '/products/ginseng-v2-03.png',
  '/products/ginseng-v2-04.jpeg',
  '/products/ginseng-v2-05.jpeg',
  '/products/ginseng-v2-06.jpeg',
  '/products/ginseng-v2-07.jpeg',
  '/products/maca-v2-01.png',
  '/products/maca-v2-02.png',
  '/products/maca-v2-03.png',
  '/products/maca-v2-04.jpeg',
  '/products/maca-v2-05.jpeg',
  '/products/maca-v2-06.jpeg',
  '/products/maca-v2-07.jpeg',
  '/products/cordyceps-v2-01.png',
  '/products/cordyceps-v2-02.png',
  '/products/cordyceps-v2-03.png',
  '/products/cordyceps-v2-04.png',
  '/products/royal-jelly-v2-01.png',
  '/products/royal-jelly-v2-02.png',
  '/products/royal-jelly-v2-03.png',
  '/products/royal-jelly-v2-04.jpeg',
  '/products/royal-jelly-v2-05.jpeg',
  '/products/royal-jelly-v2-06.jpeg',
  '/products/royal-jelly-v2-07.jpeg',
  '/products/tongkat-v2-01.png',
  '/products/tongkat-v2-02.png',
  '/products/tongkat-v2-03.png',
  '/products/tongkat-v2-04.jpeg',
  '/products/tongkat-v2-05.jpeg',
  '/products/tongkat-v2-06.jpeg',
  '/products/tongkat-v2-07.jpeg',
  '/products/liver-v2-01.png',
  '/products/liver-v2-02.png',
  '/products/liver-v2-03.png',
  '/products/liver-v2-04.png',
  '/products/liver-v2-05.jpeg',
  '/products/liver-v2-06.jpeg',
  '/products/liver-v2-07.jpeg',
  '/products/liver-v2-08.jpeg',
])

import { forwardRef } from 'react'

const Picture = forwardRef(function Picture({ src, ...imgProps }, ref) {
  if (!src || !/\.(png|jpe?g)$/i.test(src)) {
    return <img ref={ref} src={src} {...imgProps} />
  }
  const base = src.replace(/\.(png|jpe?g)$/i, '')
  const webp = `${base}.webp`
  const avif = `${base}.avif`
  const useAvif = !NO_AVIF.has(src)
  const useWebp = !NO_WEBP.has(src)
  return (
    <picture>
      {useAvif && <source type="image/avif" srcSet={avif} />}
      {useWebp && <source type="image/webp" srcSet={webp} />}
      <img ref={ref} src={src} {...imgProps} />
    </picture>
  )
})

export default Picture
